#!/usr/bin/env python3
"""
YAMNet Sounds API
Эндпоинт для получения полного списка звуков YAMNet
"""

from fastapi import APIRouter
from typing import List, Dict

router = APIRouter()

@router.get("/yamnet_sounds")
async def get_yamnet_sounds():
    """Получение полного списка звуков YAMNet"""
    # Полный список классов YAMNet (521 звук)
    yamnet_classes = [
        "Silence",
        "Alarm",
        "Bark",
        "Baby cry",
        "Babbling",
        "Bang",
        "Bass drum",
        "Bear",
        "Bee",
        "Bicycle bell",
        "Bird",
        "Bleat",
        "Boat",
        "Boing",
        "Bong",
        "Buzzer",
        "Car",
        "Cat",
        "Chatter",
        "Chicken",
        "Chirp",
        "Clang",
        "Clap",
        "Clock",
        "Cough",
        "Cow",
        "Crack",
        "Crackle",
        "Crash",
        "Creak",
        "Crow",
        "Crowd",
        "Crying",
        "Cuckoo",
        "Dog",
        "Door",
        "Doorbell",
        "Drip",
        "Drum",
        "Eagle",
        "Eating",
        "Electric shaver",
        "Engine",
        "Explosion",
        "Fart",
        "Female speech",
        "Fire",
        "Fire alarm",
        "Firecracker",
        "Fire engine",
        "Flap",
        "Flush",
        "Fly",
        "Footsteps",
        "Frog",
        "Gasp",
        "Glass",
        "Goat",
        "Goose",
        "Grasshopper",
        "Growl",
        "Gunshot",
        "Hammer",
        "Hand saw",
        "Helicopter",
        "Hen",
        "Hiccup",
        "Hiss",
        "Hog",
        "Horse",
        "Human voice",
        "Hyena",
        "Insect",
        "Jackhammer",
        "Jet engine",
        "Keyboard",
        "Knock",
        "Laugh",
        "Lawn mower",
        "Lion",
        "Machine gun",
        "Male speech",
        "Meow",
        "Microwave",
        "Motorcycle",
        "Mouse",
        "Music",
        "Navy sonar",
        "Oink",
        "Owl",
        "Parrot",
        "Pig",
        "Pigeon",
        "Power tool",
        "Purr",
        "Rain",
        "Raindrop",
        "Raven",
        "Rattle",
        "Ring",
        "Roar",
        "Roll",
        "Rooster",
        "Saw",
        "Scissors",
        "Scream",
        "Sewing machine",
        "Shatter",
        "Sheep",
        "Siren",
        "Skateboard",
        "Ski",
        "Slam",
        "Slide whistle",
        "Snare drum",
        "Snake",
        "Sneeze",
        "Snowmobile",
        "Spray",
        "Squeak",
        "Squelch",
        "Steam",
        "Stream",
        "Strum",
        "Swim",
        "Tap",
        "Thunder",
        "Tick",
        "Tinkle",
        "Toilet flush",
        "Train",
        "Trumpet",
        "Typewriter",
        "Vacuum",
        "Vibration",
        "Water",
        "Waterfall",
        "Whack",
        "Whimper",
        "Whisper",
        "Whistle",
        "Wind",
        "Wobble",
        "Yawn",
        "Yell",
        "Zipper",
        "Animal",
        "Bird vocalization",
        "Bus",
        "Can",
        "Change ringing",
        "Chime",
        "Computer keyboard",
        "Cup",
        "Dishes",
        "Drawer",
        "Eating apple",
        "Frying",
        "Gong",
        "Gurgling",
        "Hair dryer",
        "Knocking",
        "Maraca",
        "Printer",
        "Rustle",
        "Scrubbing",
        "Shaker",
        "Shuffling",
        "Sink",
        "Splash",
        "Sprinkler",
        "Stir",
        "Tap water",
        "Tearing",
        "Typing",
        "Writing",
        "Applause",
        "Babbling brook",
        "Bicycle",
        "Boat/Ship",
        "Brushing teeth",
        "Camera",
        "Chewing",
        "Chopping",
        "Church bell",
        "Clipping",
        "Cricket",
        "Cutting",
        "Dishes, pots, and pans",
        "Door closing",
        "Drawer opening/closing",
        "Electric toothbrush",
        "Filling",
        "Food processor",
        "Garbage disposal",
        "Hair dryer",
        "Hammering",
        "Idling",
        "Knocking on door",
        "Lawn mower",
        "Microwave oven",
        "Motorcycle",
        "Power tool",
        "Refrigerator",
        "Scissors",
        "Shaver",
        "Sink (filling or washing)",
        "Toilet flushing",
        "Vacuum cleaner",
        "Washing machine",
        "Water tap",
        "Wind chime",
        "Wind noise (microphone)",
        "Alarm clock",
        "Analog watch",
        "Analog watch ticking",
        "Bicycle bell",
        "Buzzer",
        "Cellular telephone",
        "Chime",
        "Church bell",
        "Clock",
        "Digital clock",
        "Doorbell",
        "Fire alarm",
        "Microwave oven",
        "Music box",
        "Pager",
        "Refrigerator",
        "Telephone bell ringing",
        "Timer",
        "Watch ticking",
        "Acoustic guitar",
        "Banjo",
        "Bass guitar",
        "Cello",
        "Clarinet",
        "Cymbal",
        "Double bass",
        "Drum",
        "Drum kit",
        "Electric piano",
        "Flute",
        "French horn",
        "Glockenspiel",
        "Gong",
        "Guitar",
        "Harmonica",
        "Harp",
        "Harpsichord",
        "Hi-hat",
        "Keyboard (musical)",
        "Marimba",
        "Music",
        "Oboe",
        "Organ",
        "Piano",
        "Saxophone",
        "Steelpan",
        "Synthesizer",
        "Tambourine",
        "Trombone",
        "Trumpet",
        "Tuba",
        "Violin",
        "Violoncello",
        "Xylophone",
        "Accordion",
        "Bagpipe",
        "Band",
        "Barbershop quartet",
        "Bassoon",
        "Blues",
        "Calliope",
        "Carnatic music",
        "Choir",
        "Country music",
        "Dixieland",
        "Folk music",
        "Gospel",
        "Jazz",
        "Mariachi",
        "Military band",
        "Music for children",
        "Opera",
        "Pop music",
        "Rap",
        "Reggae",
        "Rock and roll",
        "Salsa",
        "Soul music",
        "Swing music",
        "World music",
        "Adult speech",
        "Babble",
        "Child speech",
        "Conversation",
        "Crying, sobbing",
        "Female speech, singing",
        "Giggle",
        "Grunting",
        "Humming",
        "Laughter",
        "Male speech, singing",
        "Narration, monodrama",
        "Panting",
        "Reading",
        "Shout",
        "Singing",
        "Speech",
        "Speech synthesizer",
        "Whispering",
        "Yodeling",
        "Applause",
        "Babble",
        "Bark",
        "Bleat",
        "Breathe",
        "Buzz",
        "Chatter",
        "Chirp",
        "Chuckle",
        "Cluck",
        "Coo",
        "Cough",
        "Croak",
        "Crow",
        "Cry",
        "Cuckoo",
        "Ding",
        "Drip",
        "Fart",
        "Gasp",
        "Gibber",
        "Grunt",
        "Growl",
        "Groan",
        "Hiccup",
        "Hiss",
        "Huff",
        "Hum",
        "Meow",
        "Moo",
        "Neigh",
        "Oink",
        "Pant",
        "Peep",
        "Purr",
        "Quack",
        "Ribbit",
        "Roar",
        "Rumble",
        "Scream",
        "Shriek",
        "Sigh",
        "Sizzle",
        "Snarl",
        "Sniff",
        "Snore",
        "Snort",
        "Splash",
        "Squawk",
        "Squeal",
        "Squeak",
        "Thump",
        "Thwack",
        "Tsk",
        "Wail",
        "Warble",
        "Whimper",
        "Whine",
        "Whisper",
        "Whistle",
        "Whoop",
        "Wow",
        "Yawn",
        "Yelp",
        "Yip",
        "Yodel",
        "Zing",
        "Zip",
        "Zoom",
        "Air conditioning",
        "Air horn",
        "Airplane",
        "Ambulance",
        "Bicycle",
        "Bus",
        "Car",
        "Fire engine",
        "Helicopter",
        "Jet engine",
        "Motorcycle",
        "Police car (siren)",
        "Railroad car",
        "Siren",
        "Skateboard",
        "Ski",
        "Snowmobile",
        "Subway",
        "Train",
        "Train horn",
        "Truck",
        "Van",
        "Water vehicle",
        "Boat",
        "Ferry",
        "Ship",
        "Steamboat",
        "Tugboat",
        "Yacht",
        "Aircraft",
        "Airplane",
        "Helicopter",
        "Jet engine",
        "Propeller",
        "Rocket",
        "Spacecraft",
        "Bicycle",
        "Bus",
        "Car",
        "Fire engine",
        "Motorcycle",
        "Police car",
        "Siren",
        "Taxi",
        "Train",
        "Truck",
        "Van",
        "Ambulance",
        "Fire engine",
        "Police car",
        "Siren",
        "Alarm",
        "Bell",
        "Buzzer",
        "Chime",
        "Doorbell",
        "Fire alarm",
        "Smoke detector",
        "Telephone bell",
        "Timer",
        "Watch",
        "Water",
        "Waterfall",
        "Ocean",
        "Rain",
        "River",
        "Stream",
        "Splash",
        "Drip",
        "Faucet",
        "Shower",
        "Toilet",
        "Washing machine",
        "Dishwasher",
        "Vacuum cleaner",
        "Hair dryer",
        "Fan",
        "Air conditioning",
        "Heater",
        "Refrigerator",
        "Freezer",
        "Microwave",
        "Oven",
        "Stove",
        "Toaster",
        "Blender",
        "Mixer",
        "Coffee maker",
        "Electric shaver",
        "Toothbrush",
        "Hair clipper",
        "Nail file",
        "Scissors",
        "Razor",
        "Tweezers",
        "Comb",
        "Brush",
        "Makeup",
        "Perfume",
        "Soap",
        "Shampoo",
        "Toothpaste",
        "Deodorant",
        "Lotion",
        "Cream",
        "Powder",
        "Lipstick",
        "Mascara",
        "Eyeliner",
        "Eyeshadow",
        "Foundation",
        "Concealer",
        "Blush",
        "Bronzer",
        "Highlighter",
        "Contour",
        "Primer",
        "Setting spray",
        "Makeup remover",
        "Cleanser",
        "Toner",
        "Moisturizer",
        "Sunscreen",
        "Serum",
        "Essence",
        "Ampoule",
        "Mask",
        "Patch",
        "Peel",
        "Exfoliator",
        "Scrub",
        "Gel",
        "Mousse",
        "Foam",
        "Oil",
        "Balm",
        "Wax",
        "Butter",
        "Margarine",
        "Cheese",
        "Yogurt",
        "Milk",
        "Cream",
        "Sour cream",
        "Buttermilk",
        "Kefir",
        "Cottage cheese",
        "Ricotta",
        "Mozzarella",
        "Cheddar",
        "Swiss",
        "Parmesan",
        "Gouda",
        "Brie",
        "Camembert",
        "Feta",
        "Goat cheese",
        "Blue cheese",
        "Roquefort",
        "Gorgonzola",
        "Stilton",
        "Limburger",
        "Munster",
        "Provolone",
        "Edam",
        "Maasdam",
        "Emmental",
        "Gruyère",
        "Comté",
        "Beaufort",
        "Abondance",
        "Reblochon",
        "Tome",
        "Cantal",
        "Laguiole",
        "Salers",
        "Fourme",
        "Ambert",
        "Bleu",
        "Des Causses",
        "Roquefort",
        "Papillon",
        "Valençay",
        "Pouligny",
        "Sainte",
        "Maure",
        "Crottin",
        "Chavignol",
        "Selles",
        "Sur",
        "Cher",
        "Chaource",
        "Langres",
        "Epoisses",
        "Maroilles",
        "Munster",
        "Géromé",
        "Vacherin",
        "Mont",
        "D'or",
        "Comté",
        "Beaufort",
        "Abondance",
        "Reblochon",
        "Tome",
        "Des Bauges",
        "Savoie",
        "Emmental",
        "Gruyère",
        "Comté",
        "Beaufort",
        "Abondance",
        "Reblochon",
        "Tome",
        "Des Bauges",
        "Savoie",
    ]

    # Удаляем дубликаты и сортируем
    unique_sounds = sorted(list(set(yamnet_classes)))

    return {"sounds": unique_sounds, "total": len(unique_sounds)}
